### ISSUE TITLE
Cmake

### ISSUE THREAD

**Issue by aytaa** [knopkem/dicomweb-pacs#1]
CMake executable is not found. ! How can i resolve ?

**Comment by knopkem** [comment]
normally you should not need came. this means that either the node version or the os are not matching the prebuild packages. Usually node 12 lts on either windows or linux should work out of the box. what is your os and node version?

**Comment by aytaa** [comment]
My Os macos and node i dont know now i will write again. Is there a wado

**Comment by knopkem** [comment]
ok, for macos there is no precompiled build uploaded (because I don't have a mac). So in this case you need to install [cmake ](http://cmake.org/) and have it available in path and a working c++ compiler (clang or g++ on mac). See [dicom-dimse-native](https://github.com/knopkem/dicom-dimse-native)
