### ISSUE TITLE
Study deletion

### ISSUE THREAD

**Issue by Khanshk** [knopkem/dicomweb-pacs#2]
Hi,
As studies received in data folder , let me know how to delete studies?
Any study limit in it ?

Thanks

**Comment by knopkem** [comment]
Hi,
unfortunately, deletion is not implemented (as this is not part of
DICOMWEB), however I will put it on the roadmap.
Note that this pacs server is not yet production ready, it will work for
what is currently implemented but misses a lot of functionality.
You mentioned that you use orthanc, I would recommend to rather use the
dicomweb plugin for orthanc in this case.
https://book.orthanc-server.com/plugins/dicomweb.html
Cheers
