### ISSUE TITLE
add patient url show files

### ISSUE THREAD

**Issue by aziziseraj** [knopkem/dicomweb-pacs#43]
hi @knopkem 
how to open patient files with direct link 
for example : 

http://localhost:5001/viewer/?pid=VOha/18d81EcyTVRT2UmZA==

**Comment by knopkem** [comment]
Uh, I missed this one, sorry. Guess it's not relevant anymore, but regarding your question this has more todo with the embedded viewer (OHIF viewer) so please check there. (In fact, I don't know if this is possible with the viewer). Regards
