### ISSUE TITLE
Is it production ready ??

### ISSUE THREAD

**Issue by arunjoshtech** [knopkem/dicomweb-pacs#45]
Dear sir,
wishing and thanks for your work on Nodejs-based pacs environment.
Is it production-ready for Basic file upload from multiple gateways to store a centralized Image archive system in the Linux web server?

**Comment by knopkem** [comment]
hi, no it's not. It's not at the same feature level and robustness as other available servers (recommend  dcm4chee latest version ) and also uses SQLite which isn't great for production use
