### ISSUE TITLE
Error: Association Request failed: Failed to establish association

### ISSUE THREAD

**Issue by tiagonogueira1983** [knopkem/dicomweb-pacs#64]
root@app:/home/pacs# npx dicomweb-pacs
starting dicomweb-pacs...
stdout: 15:13:59.606 INFO  starting...

stdout: 15:13:59.631 INFO  web-server listening on port: 5001
15:13:59.631 INFO  pacs-server listening on port: 201
15:13:59.631 INFO  sending C-ECHO to target: LEXUSWEB_PACS

stdout: 15:13:59.634 INFO  {"code":1,"container":null,"message":"Request Parameters: ====================== BEGIN A-ASSOCIATE-RQ =====================\nOur Implementation Class UID:      1.2.276.0.7230010.3.0.3.6.5\nOur Implementation Version Name:   OFFIS_DCMTK_365\nTheir Implementation Class UID:    \nTheir Implementation Version Name: \nApplication Context Name:    1.2.840.10008.3.1.1.1\nCalling Application Name:    LEXUSWEB_PACS\nCalled Application Name:     LEXUSWEB_PACS\nResponding Application Name: LEXUSWEB_PACS\nOur Max PDU Receive Size:    16384\nTheir Max PDU Receive Size:  0\nPresentation Contexts:\n  Context ID:        1 (Proposed)\n    Abstract Syntax: =VerificationSOPClass\n    Proposed SCP/SCU Role: Default\n    Proposed Transfer Syntax(es):\n      =LittleEndianImplicit\nRequested Extended Negotiation: none\nAccepted Extended Negotiation:  none\nRequested User Identity Negotiation: none\nUser Identity Negotiation Response:  none\n======================= END A-ASSOCIATE-RQ ======================","status":"pending"}

stdout: 15:13:59.635 INFO  {"code":1,"container":null,"message":"Requesting Association","status":"pending"}

stdout: 15:13:59.635 INFO  {"code":2,"container":null,"message":"Association Request failed: Failed to establish association\n0006:0317 Peer aborted Association (or never connected)\n0006:031c TCP Initialization Error: Connection refused","status":"failure"}

client_loop: send disconnect: Connection reset

**Comment by knopkem** [comment]
Hi, seems like either a configuration issue or your LEXUSWEB_PACS is not listening. What is the AET, Port and IP of your PACS? and how did you configure dicomweb-pacs?

**Comment by tiagonogueira1983** [comment]
My config file on local machine:

const config = {
    
    source: {
      aet: "DICOMWEB_PACS",
      ip: "127.0.0.1",
      port: "6000"
    },
    peers: [
      {
        aet: "DICOMWEB_PROXY",
        ip: "127.0.0.1",
        port: "6000"
      }],
      
    
    // transfer syntax (e.g. compression of dicom files) used for transmission via wado and proposed to pacs
    transferSyntax: '1.2.840.10008.1.2', // attention: compression not yet working with wado-rs
    logDir: "./logs",
    storagePath: "./data",
    webserverPort: 5001,
    qidoMinChars: 0, // do not issue c-find if search contains less characters
    qidoAppendWildcard: true, // auto append * for patient name query
    permissiveMode: true, // when set to false, all AETs able to query and push need to be in peers
    verboseLogging: false // enable verbose logging to std::out (contains DIMSE output)
};

module.exports = config;
