### ISSUE TITLE
Its works

### ISSUE THREAD

**Issue by afrovita** [knopkem/dicomweb-pacs#66]
![image](https://user-images.githubusercontent.com/20376032/230426554-d4c6760e-cc0d-4f23-a855-fb05ac0bc224.png)
Thanks for your greats work.
Question about patient name not showing on the table is that related to OHIF viewer or the DICOM metadata from the PACS?
![image](https://user-images.githubusercontent.com/20376032/230427910-27d83e33-3c3c-4666-b6dc-7dc335afa137.png)

**Comment by knopkem** [comment]
Hi, which version of OHIF is this?

**Comment by afrovita** [comment]
Preinstalled OHIF DICOM Web Viewer (version 4.12.50) via git clone the repo

**Comment by afrovita** [comment]
its in _StudyListRoute.js_ OHIF viewer file, change it from
`  const mappedStudies = studies.map(study => {
    const PatientName =
      typeof study.PatientName === 'string' ? study.PatientName : undefined;
`
to
` const mappedStudies = studies.map(study => {
    const PatientName =
      typeof study.PatientName[0].Alphabetic === 'string' ?study.PatientName[0].Alphabetic : undefined;`

Thank you for your greats works and time

**Comment by knopkem** [comment]
Thanks for the investigation. It's strange that the patient name is not read correctly as it (was) written in the dicom standard (at least some years ago. Will study it again and come with a fix.

**Comment by knopkem** [comment]
The Empty Name issue should be fixed now with version 1.4.1, so you don't need your modifications anymore
