### ISSUE TITLE
change dicom viewer version

### ISSUE THREAD

**Issue by 1hilari** [knopkem/dicomweb-pacs#73]
How to change to OHIF DICOM Web Viewer version 3.7 ?

**Comment by knopkem** [comment]
In principle you just need to head over to https://github.com/OHIF/Viewers compile the latest version and replace the public folder in this repo (+ update the app-config.js inside public). Alternatively, just copy the viewer (publicI) from https://github.com/knopkem/dicomweb-proxy
However, the reason why this is still with the previous major version is that it has problems with showing none latin-1 (utf8) names properly and I haven't had the time to debug it. Also, seems like they changed the requirements for the metadata again and the latest latest version did not even run for me.

**Comment by knopkem** [comment]
In fact, I could update to the latest release version (3.7.0)
