### ISSUE TITLE
feature: support for Modality Worklists

### ISSUE THREAD

**Issue by k2s** [knopkem/dicomweb-pacs#8]
Could it be possible to serve DICOM worklists ?

**Comment by knopkem** [comment]
Interesting feature indeed, this should be possible to implement (at least similar to this: https://support.dcmtk.org/docs/wlmscpfs.html). Will look into it if there is time.

**Comment by ynakanishi1985** [comment]
Hello, your dicomweb-pacs is so great.
It is can be install with only a few commands, without any complicated setting.
Now, I have two issue as below ;

1. Delete Study

Could it be possible to delete study on dicom server ?
It is better to delete from study list.

2. Specific character set

Could it be possible to use specific character set for patient information ?
Preinstalled OHIF viewer can't show patient info in Japanese as attached picture.

I would like to use ;
ISO IR 13
ISO IR 87
ISO IR 13/87

![capture](https://user-images.githubusercontent.com/71856005/147605189-11f04c9e-e0d8-419d-b231-8ffec7924622.png)

**Comment by knopkem** [comment]
Hello @ynakanishi1985 next time please create a new issue if it is unrelated to the exitsting one.
Regarding your issues: Deleting studies, yes this is probably something missing here and somehow this never made it into the DICOM standard but is rather handled propriatory. So this would not be possible to integrate (without forking) into the OHIF viewer, but it could be a separate admin only page, will think about it.
Regarding the character set issue, this is actually not an issue coming from OHIF but rather from the [dicom-plugin](https://github.com/knopkem/dicom-dimse-native) and already on the roadmap. I will try to find some time to integrate it.
Cheers.

**Comment by ynakanishi1985** [comment]
Hello, @knopkm,
Thank you for your reply. I will create new issue for next time.
Regarding "Deleting studies" , It seems to better to delete on a separate admin only page.
I expect to be on the roadmap about it.
Regarding the character set issue, it is good news for me.
Looking forward any update or progress.

**Comment by knopkem** [comment]
Hi @ynakanishi1985 I published a new version (1.2.0) that now supports enhanced character sets. Please note that you will need to wipe and reimport your database in order for it to work. Let me know if it works for you. Besides, the default http port changed (5000 --> 5001). Good luck.
